language: c
script:
  sudo make install
branches:
  only:
  - master
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get update -qq; sudo apt-get install doxygen libpcap-dev; fi
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update; brew install doxygen; fi
install:  cd libnet && ../Prepare && ../Build
#add email if you want to get notified
#notifications:
#  email:

